### ISSUE TITLE
port packaging shell script to scheme

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#485]
**Reported by: pnkfelix  on Tue Oct 23 13:09:45 2007**
From an email exchange on August 27th, 2007

I found the place where the compilation of standard libraries (for the purposes of distribution) happens.

See the file:
	test/Scripts/package-bin-release.sh

It would probably be a great improvement to either
1. Port this shell script to run directly atop Larceny (this is now feasible since we have added the file-system library).
2. Factor out the inline Scheme code in the script into its own file (perhaps called src/Build/package-release.sch).

Either of such changes would make it much easier for future developers to add new files to the list of things to ship in compiled form.

**Comment by WillClinger** [comment]
The script's Scheme code was commented out by changeset 45b2285047cd89e9f661699de41887eb322065ca

R7RS/R6RS files are compiled by a different script using `larceny:compile-r7rs-runtime`, which automatically compiles all R7RS/R6RS libraries found within the the require path.

A similar technique could compile R5RS libraries automatically, but that won't work because many (most?) of the R5RS code in the search path is now broken or obsolete.  At the moment, we aren't compiling any R5RS code that isn't included within the standard heaps, partly because we're having platform-specific and version-specific trouble with the FFI (and the ARM version doesn't even have an FFI at the moment).

It seems, therefore, that the specific defect has been fixed.
